agent:
    name: CogagentAgent
    relative_bbox: "True"
    args:
        url: "http://172.18.192.61:24024/v1/android"

task:
    class: CogAgentTask_AutoTest
    args:
        save_dir: "./logs/evaluation"
        max_rounds: 25
        request_interval: 3
        mode: "in_app"

eval:
    avd_base: /Users/xuyifan/.android/avd
    avd_name: Pixel_7_Pro_API_33_v2
    avd_log_dir: ./logs/evaluation
    android_sdk_path: /Users/xuyifan/Library/Android/sdk
