agent:
    name: GLM4Agent
    args:
        max_new_tokens: 512

task:
    args:
        save_dir: "./logs/evaluation"
        max_rounds: 25
        request_interval: 3
        mode: "in_app"

eval:
    avd_base: /Users/xuyifan/.android/avd
    avd_name: Pixel_7_Pro_API_33_v2
    avd_log_dir: ./logs/evaluation
    android_sdk_path: /Users/xuyifan/Library/Android/sdk
