agent:
    name: OpenAIAgent
    args:
        api_key: sk-
        model_name: "gpt-4-1106-preview"
        max_new_tokens: 512

task:
    class: TextOnlyMobileTask_AutoTest
    args:
        save_dir: "./logs/evaluation"
        max_rounds: 25
        request_interval: 3

eval:
    avd_base: /Users/your user name/.android/avd
    avd_name: Pixel_7_Pro_test_device
    avd_log_dir: ./logs/avd
    android_sdk_path: /Users/your user name/Library/Android/sdk